---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ include "evroc-csi-driver.driverName" . }}
  labels:
    {{- include "evroc-csi-driver.labels" . | nindent 4 }}
spec:
  # Attach is required for block volumes
  attachRequired: {{ .Values.csiDriver.attachRequired }}

  # Pod info is not needed on mount
  podInfoOnMount: {{ .Values.csiDriver.podInfoOnMount }}

  # Volume lifecycle modes
  volumeLifecycleModes:
    {{- toYaml .Values.csiDriver.volumeLifecycleModes | nindent 4 }}

  # Filesystem group policy
  {{- if .Values.csiDriver.fsGroupPolicy }}
  fsGroupPolicy: {{ .Values.csiDriver.fsGroupPolicy }}
  {{- end }}

  # Requires republish
  requiresRepublish: {{ .Values.csiDriver.requiresRepublish }}
