// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 evroc


package evroc

import (
	"context"

	"github.com/evroc-oss/evroc-csi-driver/pkg/evroc/types"
)

// StorageBackend defines the interface for evroc storage operations.
// This interface abstracts the underlying implementation, currently using the REST API.
// All operations only affect resources managed by this CSI driver.
type StorageBackend interface {
	// EnsureDiskCreated creates a disk if it doesn't exist.
	// Returns true if the disk was created, false if it already existed.
	EnsureDiskCreated(ctx context.Context, name string, sizeMB int32, storageClass, zone string) (bool, error)

	// EnsureDiskDeleted ensures a disk is deleted.
	EnsureDiskDeleted(ctx context.Context, name string) error

	// GetDisk retrieves a disk by name. Only returns disks managed by this CSI driver.
	GetDisk(ctx context.Context, name string) (*types.Disk, error)

	// ListDisks lists all disks managed by this CSI driver.
	ListDisks(ctx context.Context) (*types.DiskList, error)

	// GetAttachment retrieves a HotswapDiskAttachment by disk and VM name.
	// Only returns attachments managed by this CSI driver.
	GetAttachment(ctx context.Context, diskName, vmName string) (*types.HotswapDiskAttachment, error)

	// ListAttachments lists all HotswapDiskAttachments managed by this CSI driver.
	ListAttachments(ctx context.Context) (*types.HotswapDiskAttachmentList, error)

	// CountNodeAttachments returns the number of volume attachments for a specific node/VM.
	// Only counts attachments managed by this CSI driver.
	CountNodeAttachments(ctx context.Context, vmName string) (int, error)

	// EnsureAttachmentCreated creates a HotswapDiskAttachment.
	// The serial will be automatically generated by the controller and populated in the status.
	EnsureAttachmentCreated(ctx context.Context, diskName, vmName string) error

	// WaitForAttachmentSerial waits for the serial to be populated in the attachment status.
	// Returns the serial once available, or an error if timeout is reached.
	WaitForAttachmentSerial(ctx context.Context, diskName, vmName string) (string, error)

	// EnsureAttachmentDeleted ensures a HotswapDiskAttachment is deleted.
	EnsureAttachmentDeleted(ctx context.Context, diskName, vmName string) error
}
