---
apiVersion: v1
kind: Service
metadata:
  name: evroc-csi-controller-metrics
  namespace: kube-system
  labels:
    app.kubernetes.io/name: evroc-csi-driver
    app.kubernetes.io/component: controller
spec:
  selector:
    app: evroc-csi-controller
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: evroc-csi-node-metrics
  namespace: kube-system
  labels:
    app.kubernetes.io/name: evroc-csi-driver
    app.kubernetes.io/component: node
spec:
  selector:
    app: evroc-csi-driver
  ports:
    - name: metrics
      port: 9091
      targetPort: 9091
      protocol: TCP
